/**
 * Curated LSV (Luis Scott-Vargas / Limited Resources) Pre-Release Ratings for Lorwyn Eclipsed (ECL).
 * Standard 0.0 - 5.0 scale with 0.5 step increments.
 */
export const ECL_LSV_DATA: Record<string, number> = {
  "Changeling Wayfinder": 3.0,
  "Rooftop Percher": 3.5,
  "Adept Watershaper": 3.5,
  "Ajani, Outland Chaperone": 4.5,
  "Appeal to Eirdu": 2.0,
  "Bark of Doran": 2.5,
  "Brigid, Clachan's Heart": 4.0,
  "Burdened Stoneback": 3.0,
  "Champion of the Clachan": 3.5,
  "Clachan Festival": 3.5,
  "Crib Swap": 2.5,
  "Curious Colossus": 4.5,
  "Eirdu, Carrier of Dawn": 4.5,
  "Encumbered Reejerey": 3.5,
  "Evershrike's Gift": 3.0,
  "Flock Impostor": 3.5,
  "Gallant Fowlknight": 3.0,
  "Goldmeadow Nomad": 3.0,
  "Keep Out": 3.0,
  "Kinbinding": 4.5,
  "Kinsbaile Aspirant": 3.5,
  "Kinscaer Sentry": 4.0,
  "Kithkeeper": 3.0,
  "Liminal Hold": 3.5,
  "Meanders Guide": 3.0,
  "Moonlit Lamenter": 3.5,
  "Morningtide's Light": 3.0,
  "Personify": 3.0,
  "Protective Response": 3.5,
  "Pyrrhic Strike": 3.5,
  "Reluctant Dounguard": 2.5,
  "Rhys, the Evermore": 3.0,
  "Riverguard's Reflexes": 2.5,
  "Shore Lurker": 3.0,
  "Slumbering Walker": 4.0,
  "Spiral into Solitude": 3.0,
  "Sun-Dappled Celebrant": 3.0,
  "Thoughtweft Imbuer": 3.5,
  "Timid Shieldbearer": 3.5,
  "Tributary Vaulter": 3.5,
  "Wanderbrine Preacher": 3.5,
  "Wanderbrine Trapper": 3.5,
  "Winnowing": 3.0,
  "Aquitect's Defenses": 3.0,
  "Blossombind": 3.5,
  "Champions of the Shoal": 4.5,
  "Disruptor of Currents": 4.5,
  "Flitterwing Nuisance": 4.0,
  "Glamer Gifter": 3.5,
  "Glamermite": 3.0,
  "Glen Elendra Guardian": 3.5,
  "Glen Elendra's Answer": 4.0,
  "Gravelgill Scoundrel": 3.5,
  "Harmonized Crescendo": 3.0,
  "Illusion Spinners": 2.5,
  "Kulrath Mystic": 3.0,
  "Loch Mare": 4.5,
  "Lofty Dreams": 3.5,
  "Mirrorform": 3.5,
  "Noggle the Mind": 3.5,
  "Oko, Lorwyn Liege": 3.5,
  "Omni-Changeling": 3.5,
  "Pestered Wellguard": 3.0,
  "Rime Chill": 3.0,
  "Rimefire Torque": 1.5,
  "Rimekin Recluse": 3.5,
  "Run Away Together": 2.0,
  "Shinestriker": 3.5,
  "Silvergill Mentor": 3.5,
  "Silvergill Peddler": 3.0,
  "Spell Snare": 2.0,
  "Stratosoarer": 3.0,
  "Summit Sentinel": 3.0,
  "Sunderflock": 4.5,
  "Swat Away": 3.0,
  "Sygg, Wanderwine Wisdom": 4.0,
  "Tanufel Rimespeaker": 3.5,
  "Temporal Cleansing": 3.5,
  "Thirst for Identity": 3.0,
  "Unexpected Assistance": 3.5,
  "Unwelcome Sprite": 3.5,
  "Wanderwine Distracter": 2.0,
  "Wanderwine Farewell": 3.5,
  "Wild Unraveling": 3.0,
  "Auntie's Sentence": 3.0,
  "Barbed Bloodletter": 2.5,
  "Bile-Vial Boggart": 2.5,
  "Bitterbloom Bearer": 3.5,
  "Blight Rot": 3.5,
  "Blighted Blackthorn": 2.5,
  "Bloodline Bidding": 4.0,
  "Boggart Mischief": 3.5,
  "Boggart Prankster": 3.0,
  "Bogslither's Embrace": 3.5,
  "Champion of the Weird": 4.0,
  "Creakwood Safewright": 3.5,
  "Darkness Descends": 2.5,
  "Dawnhand Dissident": 4.0,
  "Dawnhand Eulogist": 3.5,
  "Dose of Dawnglow": 2.5,
  "Dream Seizer": 2.5,
  "Gloom Ripper": 4.5,
  "Gnarlbark Elm": 3.0,
  "Graveshifter": 3.0,
  "Grub, Storied Matriarch": 3.5,
  "Gutsplitter Gang": 2.5,
  "Heirloom Auntie": 2.0,
  "Iron-Shield Elf": 3.5,
  "Moonglove Extractor": 3.0,
  "Moonshadow": 3.5,
  "Mornsong Aria": 2.5,
  "Mudbutton Cursetosser": 3.5,
  "Nameless Inversion": 3.5,
  "Nightmare Sower": 2.5,
  "Perfect Intimidation": 2.0,
  "Requiting Hex": 3.0,
  "Retched Wretch": 3.0,
  "Scarblade Scout": 3.5,
  "Scarblade's Malice": 3.0,
  "Shimmercreep": 3.0,
  "Taster of Wares": 4.0,
  "Twilight Diviner": 3.5,
  "Unbury": 3.5,
  "Ashling, Rekindled": 4.0,
  "Boldwyr Aggressor": 2.5,
  "Boneclub Berserker": 2.0,
  "Boulder Dash": 3.5,
  "Brambleback Brute": 3.0,
  "Burning Curiosity": 2.0,
  "Champion of the Path": 3.0,
  "Cinder Strike": 3.5,
  "Collective Inferno": 2.0,
  "Elder Auntie": 2.5,
  "End-Blaze Epiphany": 4.0,
  "Enraged Flamecaster": 3.0,
  "Explosive Prodigy": 3.5,
  "Feed the Flames": 3.0,
  "Flame-Chain Mauler": 3.0,
  "Flamebraider": 3.5,
  "Flamekin Gildweaver": 3.5,
  "Giantfall": 3.0,
  "Goatnap": 2.0,
  "Goliath Daydreamer": 3.5,
  "Gristle Glutton": 3.0,
  "Hexing Squelcher": 2.5,
  "Impolite Entrance": 1.5,
  "Kindle the Inner Flame": 3.5,
  "Kulrath Zealot": 3.5,
  "Lasting Tarfire": 2.0,
  "Lavaleaper": 2.0,
  "Meek Attack": 3.0,
  "Reckless Ransacking": 2.0,
  "Scuzzback Scrounger": 3.5,
  "Sear": 3.5,
  "Sizzling Changeling": 3.0,
  "Soul Immolation": 4.5,
  "Soulbright Seeker": 3.5,
  "Sourbread Auntie": 3.5,
  "Spinerock Tyrant": 4.5,
  "Squawkroaster": 2.5,
  "Sting-Slinger": 3.0,
  "Tweeze": 3.0,
  "Warren Torchmaster": 2.5,
  "Assert Perfection": 3.5,
  "Aurora Awakener": 4.5,
  "Bloom Tender": 3.0,
  "Blossoming Defense": 3.5,
  "Bristlebane Battler": 4.0,
  "Bristlebane Outrider": 3.5,
  "Celestial Reunion": 3.0,
  "Champions of the Perfect": 4.0,
  "Chomping Changeling": 2.5,
  "Crossroads Watcher": 3.5,
  "Dawn's Light Archer": 3.0,
  "Dundoolin Weaver": 3.5,
  "Formidable Speaker": 3.5,
  "Gilt-Leaf's Embrace": 3.0,
  "Great Forest Druid": 3.0,
  "Luminollusk": 2.5,
  "Lys Alana Dignitary": 3.5,
  "Lys Alana Informant": 3.5,
  "Midnight Tilling": 3.5,
  "Mistmeadow Council": 3.5,
  "Moon-Vigil Adherents": 3.5,
  "Morcant's Eyes": 3.5,
  "Mutable Explorer": 3.0,
  "Pitiless Fists": 3.5,
  "Prismabasher": 3.5,
  "Prismatic Undercurrents": 2.0,
  "Pummeler for Hire": 3.5,
  "Safewright Cavalry": 3.5,
  "Sapling Nursery": 3.5,
  "Selfless Safewright": 3.5,
  "Shimmerwilds Growth": 2.5,
  "Spry and Mighty": 3.0,
  "Surly Farrier": 3.0,
  "Tend the Sprigs": 2.5,
  "Thoughtweft Charge": 3.0,
  "Trystan, Callous Cultivator": 4.0,
  "Unforgiving Aim": 2.5,
  "Vinebred Brawler": 3.5,
  "Virulent Emissary": 3.5,
  "Wildvine Pummeler": 2.5,
  "Abigale, Eloquent First-Year": 4.5,
  "Ashling's Command": 4.5,
  "Boggart Cursecrafter": 3.5,
  "Bre of Clan Stoutarm": 3.5,
  "Brigid's Command": 4.0,
  "Catharsis": 3.0,
  "Chaos Spewer": 2.5,
  "Chitinous Graspling": 2.5,
  "Deceit": 4.5,
  "Deepchannel Duelist": 4.0,
  "Deepway Navigator": 3.5,
  "Doran, Besieged by Time": 4.0,
  "Dream Harvest": 2.5,
  "Eclipsed Boggart": 3.5,
  "Eclipsed Elf": 4.0,
  "Eclipsed Flamekin": 3.5,
  "Eclipsed Kithkin": 4.0,
  "Eclipsed Merrow": 4.0,
  "Emptiness": 4.0,
  "Feisty Spikeling": 2.5,
  "Figure of Fable": 4.5,
  "Flaring Cinder": 3.5,
  "Gangly Stompling": 3.0,
  "Glister Bairn": 3.0,
  "Grub's Command": 4.5,
  "High Perfect Morcant": 4.5,
  "Hovel Hurler": 3.0,
  "Kirol, Attentive First-Year": 3.0,
  "Lluwen, Imperfect Naturalist": 4.0,
  "Maralen, Fae Ascendant": 4.0,
  "Merrow Skyswimmer": 3.5,
  "Mischievous Sneakling": 3.0,
  "Morcant's Loyalist": 4.0,
  "Noggle Robber": 3.5,
  "Prideful Feastling": 3.0,
  "Raiding Schemes": 1.5,
  "Reaping Willow": 3.5,
  "Sanar, Innovative First-Year": 4.0,
  "Shadow Urchin": 3.0,
  "Stoic Grove-Guide": 3.0,
  "Sygg's Command": 4.0,
  "Tam, Mindful First-Year": 3.0,
  "Thoughtweft Lieutenant": 3.5,
  "Trystan's Command": 4.5,
  "Twinflame Travelers": 3.5,
  "Vibrance": 4.5,
  "Voracious Tome-Skimmer": 3.0,
  "Wary Farmer": 3.0,
  "Wistfulness": 4.5,
  "Chronicle of Victory": 4.5,
  "Dawn-Blessed Pennant": 3.0,
  "Firdoch Core": 2.5,
  "Foraging Wickermaw": 3.0,
  "Gathering Stone": 3.5,
  "Mirrormind Crown": 1.5,
  "Puca's Eye": 3.0,
  "Springleaf Drum": 2.5,
  "Stalactite Dagger": 2.5,
  "Blood Crypt": 3.0,
  "Eclipsed Realms": 3.0,
  "Evolving Wilds": 3.0,
  "Hallowed Fountain": 3.0,
  "Overgrown Tomb": 3.0,
  "Steam Vents": 3.0,
  "Temple Garden": 3.0,
  "Idyllic Tutor": 3.0,
  "Kinsbaile Cavalier": 3.0,
  "Mistbind Clique": 2.5,
  "Wanderwine Prophets": 2.5,
  "Bitterblossom": 4.0,
  "Faerie Macabre": 3.0,
  "Goblin Chieftain": 3.5,
  "Goblin Sharpshooter": 4.0,
  "Heat Shimmer": 3.0,
  "Devoted Druid": 2.5,
  "Helix Pinnacle": 3.0,
  "Leaf-Crowned Visionary": 4.0,
  "Regal Force": 2.5,
  "Manamorphose": 3.0,
  "Risen Reef": 4.0,
  "Slippery Bogle": 3.0,
  "Dolmen Gate": 3.0,
  "Door of Destinies": 3.0,
  "Painter's Servant": 3.0,
  "Thousand-Year Elixir": 3.0,
};
