/**
 * Curated LSV (Luis Scott-Vargas / Limited Resources) Pre-Release Ratings for The Hobbit (HOB).
 * Standard 0.0 - 5.0 scale with 0.5 step increments.
 */
export const HOB_LSV_DATA: Record<string, number> = {
  "Long-Bodied Grey Dog": 3.0,
  "Old Thrush": 3.0,
  "Troop of Ponies": 3.0,
  "Belladonna Took": 3.0,
  "Bilbo's Gambit": 2.0,
  "Bofur, Reliable Guardian": 3.5,
  "Celebrate the Mountain-king": 4.0,
  "D\u00e1in, Lord of the Iron Hills": 3.0,
  "Dwarven Provisioner": 3.5,
  "Dwarven Shortsword": 3.0,
  "Eagle of the Great Shelf": 2.5,
  "The Eagles Are Coming!": 4.0,
  "Esgaroth Garrison": 3.0,
  "F\u00edli the Pathfinder": 4.5,
  "Gleaming Splendor": 1.5,
  "Iron Hills Blacksmith": 3.5,
  "K\u00edli the Resourceful": 4.5,
  "Lake-town Lookout": 2.0,
  "Lake-town Toymaker": 3.0,
  "Magnificent End": 3.5,
  "Moment of Glory": 2.0,
  "The Mountain-king's Return": 4.0,
  "Ori, Keeper of Songs": 3.0,
  "The Queen of Dale": 4.0,
  "Roads Go Ever, Ever On": 3.5,
  "Settle the Wreckage": 4.0,
  "Stone by Sunlight": 3.5,
  "Thorin's Last Stand": 2.0,
  "An Unexpected Party": 4.5,
  "Velvetwing Butterflies": 3.0,
  "Vow to Erebor": 2.0,
  "Bilbo, Luckwearer": 3.5,
  "Bilbo, Thief in the Night": 4.0,
  "Bilbo Baggins, Burglar": 3.5,
  "Confusticate and Bebother": 3.0,
  "Elrond, Moon-Reader": 2.5,
  "Elven Raft-Steerer": 2.5,
  "Elvenking's Harper": 2.5,
  "Enchanted River's Grasp": 3.5,
  "Fateful Discovery": 3.0,
  "Gandalf, Wandering Wizard": 2.0,
  "Great Gilded Boat": 4.5,
  "Lakeshore Apothecary": 3.5,
  "Lake-town Mariners": 2.5,
  "Long Lake Nuisance": 3.5,
  "The Lord of the Eagles": 3.0,
  "Master's Councillors": 3.5,
  "Mirkwood Meditator": 2.0,
  "Most Decrepit Old Bird": 3.5,
  "Old Fat Spider Can't See Me": 3.0,
  "Plunder the Trollshaws": 3.5,
  "Ravenhill Flock": 2.5,
  "Riddles in the Dark": 2.5,
  "Roll-Roll-Roll-Roll": 1.5,
  "Sound the Trumpets": 3.5,
  "Thranduil's Decree": 2.5,
  "Uncover the Moon-Letters": 2.5,
  "Uneasy Partings": 3.5,
  "Wizard's Staff": 1.5,
  "Along the Crooked Way": 2.5,
  "Azog, Moria's Ruin": 3.0,
  "Bilbo's Deadly Slice": 3.5,
  "Crude Bent Blade": 3.5,
  "Desolation Prowler": 4.0,
  "Down, Down to Goblin-town": 3.5,
  "Dreaded Bat-Cloud": 3.5,
  "Front Porch Sentries": 3.0,
  "Gathering of Darkness": 3.0,
  "Gnashing of Teeth": 3.5,
  "Gollum, Riddle Master": 4.5,
  "Gollum, Silent Slinker": 3.5,
  "Gollum the Abandoned": 3.5,
  "Great Fierce Bee": 3.0,
  "Great Ugly-Looking Goblin": 3.5,
  "Head of the Hunt": 4.5,
  "Inside Information": 2.0,
  "The Master of Lake-town": 3.0,
  "Nighthowl Pursuer": 3.5,
  "Rage into the Valley": 3.5,
  "Ravening Warg": 3.5,
  "Reverent Howl": 3.0,
  "Rhovanion Rampager": 4.5,
  "The Sackville-Bagginses": 4.0,
  "Stir Up Trouble": 3.5,
  "Stony-Voiced Goblins": 3.5,
  "Supper for Spiders": 1.5,
  "Balin, Loremaster": 2.5,
  "Bombur, Gentle Dreamer": 3.0,
  "Bothersome Noisemaker": 3.5,
  "Burn, Burn, Tree and Fern": 3.5,
  "D\u00e1in Ironfoot": 4.5,
  "Desert Were-Worm": 2.0,
  "Desolation of Smaug": 3.0,
  "Dori, Bearer of Friends": 3.5,
  "Dwarven Mauler": 3.5,
  "Gandalf, Goblins' Bane": 3.5,
  "Gandalf, Spark Starter": 3.5,
  "Getaway Barrel": 3.0,
  "Gl\u00f3in the Mighty": 3.5,
  "Goblin-town Flunkies": 3.0,
  "Gundabad Opportunist": 3.5,
  "Iron Hills Stalwart": 2.5,
  "Last Light of Durin's Day": 1.5,
  "The Misty Mountains Cold": 3.5,
  "Misty Mountains Raider": 3.5,
  "\u00d3in the Brave": 3.0,
  "Pinecone Strike": 3.5,
  "Ragged Short Spear": 3.5,
  "Smaug, the Great Calamity": 3.5,
  "Smaug the Magnificent": 4.5,
  "Smaug's Fury": 2.0,
  "Snowslope Hunter": 3.0,
  "Stone-Giant of High Pass": 4.0,
  "Thorin, Mountain-king": 4.5,
  "Tidings of War": 3.5,
  "Attercop": 3.5,
  "Bejeweled Warg": 4.0,
  "Beorn, Reluctant Host": 2.5,
  "Beorn the Fierce": 4.5,
  "Beorn's Hospitality": 3.0,
  "Boughside Wanderers": 3.0,
  "Cantankerous Keepers": 3.0,
  "Dancing from Dark to Dawn": 4.5,
  "Down in the Valley": 3.5,
  "Galion, Elvenking's Butler": 3.0,
  "Gigantic Big Bear": 2.5,
  "Guardian of the Halls": 3.0,
  "Little Bear": 2.5,
  "Mirkwood Pathmaker": 3.5,
  "Nasty Little Rabbit": 3.5,
  "The Notary Hobbits": 2.5,
  "Old Fat Spider": 3.0,
  "Ordinary Bear": 3.0,
  "Part in Friendship": 2.5,
  "Quarrel": 3.5,
  "Radagast of Rhosgobel": 2.5,
  "Through the Forest Gate": 2.0,
  "Troll Negotiations": 3.0,
  "Warg Tactics": 3.0,
  "Wargling": 3.0,
  "Wilderland Scrounger": 2.5,
  "Wood Elves": 3.0,
  "Woodland Weavemaster": 3.0,
  "Bard, King of Dale": 2.5,
  "Bard the Bowman": 3.5,
  "Bard's Company": 4.5,
  "Bifur, Melodic Rider": 3.0,
  "Bolg of the North": 3.0,
  "Bolg's Company": 2.5,
  "The Chief Warg": 3.0,
  "Chief Warg's Company": 4.5,
  "D\u00e1in's Company": 4.5,
  "Duskwatch Hunter": 3.5,
  "Dwalin, Weaponmaster": 4.0,
  "Eagle's Rescue": 3.5,
  "Fearsome Goblin Pair": 3.0,
  "Goblin Plate Mail": 3.5,
  "The Great Goblin": 3.5,
  "Large Bear": 3.5,
  "Mirkwood Nurturer": 3.5,
  "Nori, Teller of Tales": 3.0,
  "Patient Instructor": 3.5,
  "Silvan Reveler": 3.0,
  "Smaug, Wicked Worm": 3.0,
  "Thorin Oakenshield": 3.5,
  "Thranduil, Sindarin Liege": 3.5,
  "Thranduil, the Elvenking": 1.5,
  "Thranduil's Company": 4.5,
  "Tom, Bert, and William": 3.5,
  "The Arkenstone": 4.5,
  "The Black Arrow": 2.5,
  "Dwarven Mattock": 3.5,
  "Giant's Boulder": 2.5,
  "Glamdring, Foe-hammer": 1.5,
  "Key to the Side-Door": 2.0,
  "My Precious": 2.5,
  "Orcrist, Goblin-cleaver": 2.5,
  "Sting, Bilbo's Sword": 2.0,
  "Thr\u00f3r's Map": 3.0,
  "Well-Worn Spatula": 2.5,
  "Elven Passage": 3.0,
  "Elvenking's Halls": 3.0,
  "Goblin-town": 3.0,
  "Hobbit Hole": 3.5,
  "Iron Hills": 3.0,
  "Lake-town": 3.5,
  "The Lonely Mountain": 4.0,
  "Mirkwood": 3.5,
};
