/**
 * Curated LSV (Luis Scott-Vargas / Limited Resources) Pre-Release Ratings for Secrets of Strixhaven (SOS).
 * Standard 0.0 - 5.0 scale with 0.5 step increments.
 */
export const SOS_LSV_DATA: Record<string, number> = {
  "The Dawning Archaic": 3.0,
  "Rancorous Archaic": 2.5,
  "Sundering Archaic": 3.5,
  "Together as One": 4.5,
  "Transcendent Archaic": 3.5,
  "Ajani's Response": 3.5,
  "Antiquities on the Loose": 4.5,
  "Ascendant Dustspeaker": 3.5,
  "Daydream": 2.0,
  "Dig Site Inventory": 3.5,
  "Eager Glyphmage": 3.5,
  "Elite Interceptor": 3.5,
  "Emeritus of Truce": 4.0,
  "Ennis, Debate Moderator": 2.5,
  "Erode": 3.5,
  "Graduation Day": 2.5,
  "Group Project": 3.5,
  "Harsh Annotation": 2.5,
  "Honorbound Page": 3.0,
  "Informed Inkwright": 4.5,
  "Inkshape Demonstrator": 3.5,
  "Interjection": 3.0,
  "Joined Researchers": 3.0,
  "Owlin Historian": 3.5,
  "Practiced Offense": 4.5,
  "Primary Research": 3.0,
  "Quill-Blade Laureate": 3.5,
  "Rapier Wit": 3.0,
  "Rehearsed Debater": 3.0,
  "Restoration Seminar": 3.5,
  "Shattered Acolyte": 3.5,
  "Soaring Stoneglider": 3.0,
  "Spiritcall Enthusiast": 2.5,
  "Stand Up for Yourself": 3.5,
  "Stirring Hopesinger": 4.5,
  "Stone Docent": 3.5,
  "Summoned Dromedary": 3.0,
  "Banishing Betrayal": 3.5,
  "Brush Off": 3.5,
  "Campus Composer": 3.0,
  "Chase Inspiration": 2.5,
  "Deluge Virtuoso": 2.5,
  "Divergent Equation": 3.5,
  "Echocasting Symposium": 4.0,
  "Emeritus of Ideation": 5.0,
  "Encouraging Aviator": 2.5,
  "Essence Scatter": 3.5,
  "Exhibition Tidecaller": 4.0,
  "Flow State": 3.5,
  "Fractal Anomaly": 2.0,
  "Fractalize": 2.5,
  "Harmonized Trio": 3.0,
  "Homesickness": 3.5,
  "Hydro-Channeler": 3.0,
  "Jadzi, Steward of Fate": 4.0,
  "Landscape Painter": 3.0,
  "Mana Sculpt": 3.5,
  "Mathemagics": 4.5,
  "Matterbending Mage": 3.5,
  "Muse Seeker": 3.0,
  "Muse's Encouragement": 2.5,
  "Orysa, Tide Choreographer": 3.0,
  "Pensive Professor": 4.0,
  "Procrastinate": 3.0,
  "Quick Study": 3.5,
  "Run Behind": 3.5,
  "Skycoach Conductor": 3.5,
  "Spellbook Seeker": 2.5,
  "Tester of the Tangential": 3.0,
  "Textbook Tabulator": 3.0,
  "Wisdom of Ages": 3.5,
  "Adventurous Eater": 3.0,
  "Arcane Omens": 3.5,
  "Arnyn, Deathbloom Botanist": 2.5,
  "Burrog Banemaker": 3.0,
  "Cheerful Osteomancer": 2.5,
  "Cost of Brilliance": 3.5,
  "Decorum Dissertation": 3.5,
  "Dissection Practice": 3.5,
  "Emeritus of Woe": 4.5,
  "End of the Hunt": 3.5,
  "Eternal Student": 3.0,
  "Foolish Fate": 3.5,
  "Forum Necroscribe": 2.5,
  "Grave Researcher": 3.5,
  "Last Gasp": 3.5,
  "Lecturing Scornmage": 3.5,
  "Leech Collector": 2.5,
  "Masterful Flourish": 3.5,
  "Melancholic Poet": 3.5,
  "Moseo, Vein's New Dean": 4.0,
  "Poisoner's Apprentice": 3.5,
  "Postmortem Professor": 4.0,
  "Pox Plague": 3.0,
  "Pull from the Grave": 3.0,
  "Rabid Attack": 2.5,
  "Ral Zarek, Guest Lecturer": 3.5,
  "Scathing Shadelock": 3.0,
  "Scheming Silvertongue": 4.0,
  "Send in the Pest": 3.0,
  "Sneering Shadewriter": 3.0,
  "Tragedy Feaster": 3.5,
  "Ulna Alley Shopkeep": 2.0,
  "Wander Off": 3.5,
  "Withering Curse": 3.0,
  "Ancestral Anger": 2.5,
  "Archaic's Agony": 3.5,
  "Artistic Process": 3.5,
  "Blazing Firesinger": 2.5,
  "Charging Strifeknight": 3.5,
  "Choreographed Sparks": 1.5,
  "Duel Tactics": 3.0,
  "Emeritus of Conflict": 3.0,
  "Expressive Firedancer": 3.5,
  "Flashback": 3.0,
  "Garrison Excavator": 3.5,
  "Goblin Glasswright": 3.0,
  "Heated Argument": 3.5,
  "Impractical Joke": 3.5,
  "Improvisation Capstone": 4.5,
  "Living History": 3.5,
  "Maelstrom Artisan": 2.5,
  "Magmablood Archaic": 3.5,
  "Mica, Reader of Ruins": 3.0,
  "Molten-Core Maestro": 4.0,
  "Pigment Wrangler": 2.5,
  "Rearing Embermare": 2.0,
  "Rubble Rouser": 3.5,
  "Seize the Spoils": 3.0,
  "Steal the Show": 3.0,
  "Strife Scholar": 2.0,
  "Tablet of Discovery": 3.5,
  "Tackle Artist": 3.0,
  "Thunderdrum Soloist": 3.5,
  "Tome Blast": 3.5,
  "Unsubtle Mockery": 3.5,
  "Zealous Lorecaster": 3.0,
  "Aberrant Manawurm": 2.5,
  "Additive Evolution": 3.5,
  "Ambitious Augmenter": 4.0,
  "Burrog Barrage": 3.5,
  "Chelonian Tackle": 2.5,
  "Comforting Counsel": 1.5,
  "Efflorescence": 2.0,
  "Emeritus of Abundance": 4.5,
  "Emil, Vastlands Roamer": 3.0,
  "Environmental Scientist": 4.0,
  "Follow the Lumarets": 2.0,
  "Germination Practicum": 4.5,
  "Glorious Decay": 2.0,
  "Hungry Graffalon": 2.0,
  "Infirmary Healer": 3.0,
  "Lumaret's Favor": 2.5,
  "Mindful Biomancer": 3.0,
  "Noxious Newt": 3.5,
  "Oracle's Restoration": 2.0,
  "Pestbrood Sloth": 3.5,
  "Planar Engineering": 3.5,
  "Shopkeeper's Bane": 3.0,
  "Slumbering Trudge": 4.0,
  "Snarl Song": 4.0,
  "Studious First-Year": 3.5,
  "Tenured Concocter": 2.5,
  "Thornfist Striker": 3.5,
  "Topiary Lecturer": 3.0,
  "Vastlands Scavenger": 3.5,
  "Wild Hypothesis": 3.0,
  "Wildgrowth Archaic": 3.5,
  "Zimone's Experiment": 3.0,
  "Abigale, Poet Laureate": 3.0,
  "Abstract Paintmage": 2.5,
  "Applied Geometry": 3.5,
  "Ark of Hunger": 4.5,
  "Aziza, Mage Tower Captain": 3.0,
  "Berta, Wise Extrapolator": 3.5,
  "Blech, Loafing Pest": 4.0,
  "Bogwater Lumaret": 3.5,
  "Borrowed Knowledge": 2.0,
  "Cauldron of Essence": 3.0,
  "Colorstorm Stallion": 4.5,
  "Colossus of the Blood Age": 3.5,
  "Conciliator's Duelist": 4.0,
  "Cuboid Colony": 3.5,
  "Dina's Guidance": 1.5,
  "Elemental Mascot": 3.0,
  "Embrace the Paradox": 3.5,
  "Essenceknit Scholar": 3.5,
  "Fix What's Broken": 2.0,
  "Fractal Mascot": 3.0,
  "Fractal Tender": 3.0,
  "Geometer's Arthropod": 3.0,
  "Grapple with Death": 3.5,
  "Growth Curve": 2.0,
  "Hardened Academic": 4.0,
  "Imperious Inkmage": 3.5,
  "Inkling Mascot": 3.5,
  "Killian's Confidence": 3.5,
  "Kirol, History Buff": 3.5,
  "Lluwen, Exchange Student": 3.5,
  "Lorehold Charm": 3.0,
  "Lorehold, the Historian": 4.0,
  "Mind into Matter": 3.5,
  "Mind Roots": 3.0,
  "Molten Note": 3.5,
  "Moment of Reckoning": 4.5,
  "Nita, Forum Conciliator": 2.5,
  "Old-Growth Educator": 3.0,
  "Paradox Surveyor": 3.5,
  "Pest Mascot": 3.0,
  "Practiced Scrollsmith": 3.5,
  "Prismari Charm": 3.5,
  "Prismari, the Inspiration": 3.0,
  "Proctor's Gaze": 3.5,
  "Professor Dellian Fel": 4.5,
  "Pterafractyl": 3.0,
  "Pursue the Past": 3.5,
  "Quandrix Charm": 3.5,
  "Quandrix, the Proof": 4.5,
  "Rapturous Moment": 3.0,
  "Render Speechless": 3.5,
  "Resonating Lute": 3.5,
  "Root Manipulation": 3.0,
  "Sanar, Unfinished Genius": 3.5,
  "Scolding Administrator": 3.5,
  "Silverquill Charm": 3.5,
  "Silverquill, the Disputant": 3.5,
  "Snooping Page": 3.5,
  "Social Snub": 2.5,
  "Spectacular Skywhale": 3.0,
  "Spirit Mascot": 3.5,
  "Splatter Technique": 4.0,
  "Stadium Tidalmage": 3.0,
  "Startled Relic Sloth": 3.5,
  "Stirring Honormancer": 3.5,
  "Stress Dream": 3.5,
  "Suspend Aggression": 3.5,
  "Tam, Observant Sequencer": 3.0,
  "Teacher's Pest": 3.0,
  "Traumatic Critique": 4.0,
  "Vibrant Outburst": 3.5,
  "Vicious Rivalry": 4.0,
  "Visionary's Dance": 3.5,
  "Wilt in the Heat": 3.5,
  "Witherbloom Charm": 3.0,
  "Witherbloom, the Balancer": 2.5,
  "Zaffai and the Tempests": 2.5,
  "Biblioplex Tomekeeper": 1.5,
  "Diary of Dreams": 2.5,
  "Mage Tower Referee": 2.5,
  "Page, Loose Leaf": 2.5,
  "Potioner's Trove": 3.5,
  "Strixhaven Skycoach": 3.5,
  "Deathcap Glade": 3.5,
  "Dreamroot Cascade": 3.5,
  "Fields of Strife": 3.5,
  "Forum of Amity": 3.5,
  "Great Hall of the Biblioplex": 4.0,
  "Paradox Gardens": 3.5,
  "Petrified Hamlet": 1.5,
  "Shattered Sanctum": 3.5,
  "Skycoach Waypoint": 2.0,
  "Spectacle Summit": 3.5,
  "Stormcarved Coast": 3.5,
  "Sundown Pass": 3.5,
  "Terramorphic Expanse": 3.5,
  "Titan's Grave": 3.5,
  "Akroma's Will": 4.0,
  "Angel's Grace": 3.0,
  "Armageddon": 2.5,
  "Duty Beyond Death": 2.5,
  "Helping Hand": 3.0,
  "Hop to It": 3.5,
  "Prismatic Ending": 3.5,
  "Repel Calamity": 3.5,
  "Reprieve": 4.0,
  "Requisition Raid": 2.5,
  "Return to the Ranks": 2.5,
  "Winds of Abandon": 4.5,
  "Brain Freeze": 3.5,
  "Cyclonic Rift": 4.0,
  "Daze": 4.0,
  "Deduce": 3.5,
  "Disdainful Stroke": 3.5,
  "Flusterstorm": 2.0,
  "Force of Will": 3.5,
  "Pongify": 2.0,
  "Preordain": 3.5,
  "Sleight of Hand": 3.5,
  "Spell Pierce": 3.5,
  "Stock Up": 3.5,
  "Ad Nauseam": 3.0,
  "Bitter Triumph": 3.5,
  "Culling the Weak": 3.0,
  "Dismember": 4.5,
  "Feed the Swarm": 3.5,
  "Living End": 3.0,
  "Locust Spray": 3.0,
  "Sheoldred's Edict": 3.0,
  "Smallpox": 2.0,
  "Stargaze": 3.5,
  "Vampiric Tutor": 2.0,
  "Zombify": 2.0,
  "Abrade": 3.5,
  "Big Score": 3.5,
  "Brotherhood's End": 4.0,
  "Bulk Up": 2.5,
  "Burst Lightning": 3.5,
  "Crackle with Power": 4.5,
  "Empty the Warrens": 3.5,
  "Jeska's Will": 2.5,
  "Monstrous Rage": 3.5,
  "Pyretic Ritual": 2.0,
  "Return the Favor": 3.0,
  "Subterranean Tremors": 4.0,
  "Awaken the Woods": 3.0,
  "Berserk": 2.0,
  "Crop Rotation": 1.5,
  "Giant Growth": 2.5,
  "Glimpse of Nature": 3.0,
  "Knockout Maneuver": 3.5,
  "Pick Your Poison": 2.0,
  "Royal Treatment": 3.5,
  "Shamanic Revelation": 2.5,
  "Shared Roots": 3.5,
  "Triumph of the Hordes": 2.0,
  "Veil of Summer": 2.5,
  "Bring to Light": 3.0,
  "Culling Ritual": 3.0,
  "Deflecting Palm": 2.0,
  "Expressive Iteration": 3.5,
  "Fracture": 2.0,
  "Archaeomancer": 3.0,
  "Archmage Emeritus": 2.5,
  "Murmuring Mystic": 3.5,
  "Grim Haruspex": 3.0,
  "Dualcaster Mage": 2.5,
  "Magus of the Library": 1.5,
  "Sylvan Library": 2.5,
  "Adrix and Nev, Twincasters": 2.0,
  "Codie, Vociferous Codex": 3.0,
  "Library of Alexandria": 4.0,
};
